django/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.index, name='index'),
    path('view/<id>', views.view_employee, name='view_employee'),
    path('edit/<pk>', views.EmployeeEditView.as_view(), name='edit_employee'),
    path('delete/<pk>', views.EmployeeDeleteView.as_view(), name='delete_employee'),
    path('password/<pk>', views.employee_change_password, name='employee_change_password'),
    path('add', views.EmployeeCreateView.as_view(), name='add_employee'),
    path('groups/add', views.GroupCreateView.as_view(), name='add_group'),
    path('groups/view/<id>', views.view_group, name='view_group'),
    path('groups/edit/<pk>', views.GroupEditView.as_view(), name='edit_group'),
    path('groups/delete/<pk>', views.GroupDeleteView.as_view(), name='delete_group'),
]

django/holiday/urls.py
from django.urls import path
from . import views

app_name = 'holiday'

urlpatterns = [
    path('', views.index, name='index'),
]

django/hr_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.apps import apps as django_apps

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main_site.urls', namespace='main_site')),
]

for app in django_apps.get_app_configs():
    if getattr(app, 'in_menu', False):
        urlpatterns.append(path(f"{app.label}/", include((f"{app.name}.urls", app.label), namespace=app.label)))

django/main_site/urls.py
from django.urls import path
from . import views

app_name = 'main_site'

urlpatterns = [
    path('', views.index, name="index"),
]

django/employees/models.py
from django.db import models


# Create your models here.

django/holiday/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Holiday(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='holiday')
    start = models.DateTimeField()
    end = models.DateTimeField()
    reason = models.TextField()

    def __str__(self):
        return f"{self.employee.first_name}: {self.start} - {self.end}"

django/main_site/models.py
from django.db import models

# Create your models here.

django/employees/forms.py
from django import forms
from . import models


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = models.Employee
        fields = ('name',)

django/employees/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AdminPasswordChangeForm


@permission_required("auth.view_user")
@permission_required("auth.view_group")
def index(request):
    employees = User.objects.all()
    groups = Group.objects.all()
    return render(request, 'employees/index.html', {"employees": employees, "groups": groups})


@permission_required("auth.view_user")
def view_employee(request, id):
    employee = get_object_or_404(User, id=id)
    return render(request, 'employees/view_employee.html', {"employee": employee})


@permission_required("auth.view_group")
def view_group(request, id):
    group = get_object_or_404(Group, id=id)
    return render(request, 'employees/view_group.html', {"group": group})


class EmployeeCreateView(LoginRequiredMixin, CreateView):
    model = User
    fields = ('username', 'password', 'first_name', 'last_name', 'is_superuser', 'groups', 'user_permissions',)
    permission_required = ('auth.add_user', )
    success_url = reverse_lazy('employees:index')
    template_name = "employees/employee_form.html"

    def form_valid(self, form):
        super().form_valid(form)
        password = self.object.password
        self.object.set_password(password)
        self.object.save()


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    fields = ('name', 'permissions',)
    permission_required = ('auth.add_group', )
    success_url = reverse_lazy('employees:index')
    template_name = "employees/group_form.html"


class EmployeeEditView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('username', 'first_name', 'last_name', 'is_active', 'is_superuser', 'groups', 'user_permissions',
              'last_login', 'date_joined',)
    success_url = reverse_lazy('employees:index')
    permission_required = ('auth.change_user', )
    template_name = "employees/employee_update_form.html"


class GroupEditView(LoginRequiredMixin, UpdateView):
    model = Group
    fields = ('name', 'permissions',)
    success_url = reverse_lazy('employees:index')
    permission_required = ('auth.change_group', )
    template_name = "employees/group_update_form.html"


@permission_required("auth.change_user")
def employee_change_password(request, pk):
    user = get_object_or_404(User, id=pk)
    if request.method == 'POST':
        form = AdminPasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = AdminPasswordChangeForm(user)
    return render(request, 'employees/employee_change_password.html', {
        'form': form,
        'object': user,
    })


class EmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('employees:index')
    permission_required = ('auth.delete_user', )
    template_name = "employees/employee_confirm_delete.html"


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('employees:index')
    permission_required = ('auth.delete_group', )
    template_name = "employees/group_confirm_delete.html"

django/holiday/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
from . import models


@permission_required("holiday.view_holiday")
def index(request):
    holiday = models.Holiday.objects.all()
    return render(request, "holiday/index.html", {
        "holiday": holiday
    })

django/main_site/views.py
from django.shortcuts import render

def index(request):
    return render(request, "main_site/index.html")

django/employees/templates/employees/employee_change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Change password for {{ object.first_name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Change password for {{ object.first_name }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
              <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/employee_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete {{ employee.first_name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
              <form method="post">
                  {% csrf_token %}
                  <h3>Are you sure you want to delete "{{ object.first_name }}"?</h3>
                  <input type="submit" class="btn btn-danger" value="Confirm">
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/employee_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add employee{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Add Employee</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
              <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/employee_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit {{ object.first_name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Edit {{ object.first_name }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
              <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/group_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete {{ employee.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
              <form method="post">
                  {% csrf_token %}
                  <h3>Are you sure you want to delete "{{ object.name }}"?</h3>
                  <input type="submit" class="btn btn-danger" value="Confirm">
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/group_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add group{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Add Group</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
              <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/group_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit {{ object.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Edit {{ object.name }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
              <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
              </form>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}Employees{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Employee managment</h1>
            </div>
            {% if perms.auth.add_user %}
                <div class="col-1">
                    <a href="{% url 'employees:add_employee' %}" class="btn btn-success">Add</a>
                </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for employee in employees %}
                        <tr>
                            <th scope="row">
                                <a href="{% url 'employees:view_employee' employee.id %}">{{ employee.id }}</a>
                            </th>
                            <td>{{ employee.first_name }}</td>
                            <td>{{ employee.last_name }}</td>
                            <td>{{ employee.email }}</td>
                            <td>
                                {% if perms.auth.change_user %}
                                    <a href="{% url "employees:edit_employee" employee.id %}" class="btn btn-primary">
                                        Edit
                                    </a>
                                    <a href="{% url "employees:employee_change_password" employee.id %}" class="btn btn-secondary">
                                        Change password
                                    </a>
                                {% endif %}
                                {% if perms.auth.delete_user %}
                                    <a href="{% url 'employees:delete_employee' employee.id %}" class="btn btn-danger">
                                        Delete
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <h1>Groups</h1>
            </div>
            {% if perms.auth.add_group %}
                <div class="col-1">
                    <a href="{% url 'employees:add_group' %}" class="btn btn-success">Add</a>
                </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for group in groups %}
                        <tr>
                            <th scope="row">
                                <a href="{% url 'employees:view_group' group.id %}">{{ group.id }}</a>
                            </th>
                            <td>{{ group.name }}</td>
                            <td>
                                {% if perms.auth.change_group %}
                                    <a href="{% url "employees:edit_group" group.id %}" class="btn btn-primary">
                                        Edit
                                    </a>
                                {% endif %}
                                {% if perms.auth.delete_group %}
                                    <a href="{% url 'employees:delete_group' group.id %}" class="btn btn-danger">
                                        Delete
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/view_employee.html
{% extends 'base.html' %}

{% block title %}{{ employee.first_name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Employee #{{ employee.id }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                  <tbody>
                        <tr>
                          <th scope="row">Username</th>
                          <td>{{ employee.username }}</td>
                        </tr>
                        <tr>
                          <th scope="row">First Name</th>
                          <td>{{ employee.first_name }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Last Name</th>
                          <td>{{ employee.last_name }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Acive</th>
                          <td>{{ employee.is_active }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Superuser</th>
                          <td>{{ employee.is_superuser }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Groups</th>
                          <td>
                              {% for group in employee.groups.all %}
                                  {{ group }}
                                  {% if not forloop.last %}
                                      <br>
                                  {% endif %}
                              {% endfor %}
                          </td>
                        </tr>
                        <tr>
                          <th scope="row">User permissions</th>
                          <td>
                              {% for perm in employee.user_permissions.all %}
                                  {{ perm }}
                                  {% if not forloop.last %}
                                      <br>
                                  {% endif %}
                              {% endfor %}
                          </td>
                        </tr>
                        <tr>
                          <th scope="row">Date joined</th>
                          <td>{{ employee.date_joined }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Last login</th>
                          <td>{{ employee.last_login }}</td>
                        </tr>
                  </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url "employees:edit_employee" employee.id %}" class="btn btn-primary">Edit</a>
            </div>
        </div>
    </div>
{% endblock %}

django/employees/templates/employees/view_group.html
{% extends 'base.html' %}

{% block title %}{{ group.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Group #{{ employee.id }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                  <tbody>
                        <tr>
                          <th scope="row">Name</th>
                          <td>{{ group.name }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Permissions</th>
                          <td>
                              {% for perm in group.permissions.all %}
                                  {{ perm }}
                                  {% if not forloop.last %}
                                      <br>
                                  {% endif %}
                              {% endfor %}
                          </td>
                        </tr>
                  </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url "employees:edit_group" group.id %}" class="btn btn-primary">Edit</a>
            </div>
        </div>
    </div>
{% endblock %}

django/holiday/templates/holiday/index.html
{% extends 'base.html' %}

{% block title %}Holiday{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Holiday</h1>
            </div>
            {% if perms.holiday.add_holiday %}
                <div class="col-1">
                    <a href="{% url 'employees:add_employee' %}" class="btn btn-success">Add</a>
                </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Employee</th>
                        <th scope="col">Start</th>
                        <th scope="col">End</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

django/main_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Home{% endblock %} | HR System</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <a href="{% url 'main_site:index' %}" class="navbar-brand">HR System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
            {% for item in menu %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ item.url }}">{{ item.name }}</a>
                </li>
            {% endfor %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'password_change'%}">Change password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout'%}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

django/main_site/templates/main_site/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>Please select an app from the menu above</h1>
        </div>
    </div>
{% endblock %}